version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=proyecto_aula
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_backend
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

volumes:
  mysql_data:
